name: ridenepal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  bottom_navy_bar: ^6.0.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.2
  get_storage: ^2.1.1
  http: ^1.1.0
  simple_fontellico_progress_dialog: ^0.3.0
  url_launcher: ^6.0.12
  khalti_flutter: ^3.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  favorite_button: ^0.0.4
  expandable_text: ^2.3.0
  intl: ^0.18.1
  esewa_flutter_sdk: ^2.0.1
  gif: ^2.3.0
  async: ^2.11.0
  path: ^1.9.0
  otp: ^3.1.4
  mailer: ^6.1.0
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.png"

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 100
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 200
      - asset: assets/fonts/Roboto-BoldCondensed.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Condensed.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 500
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 600
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 700
      - asset: assets/fonts/Roboto-Thin.ttf
        weight: 800

  - family: WorkSans
    fonts:
      - asset: assets/fonts/WorkSans-Light.ttf
        weight: 300
      - asset: assets/fonts/WorkSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/WorkSans-Bold.ttf
        weight: 500
      - asset: assets/fonts/WorkSans-ExtraBold.ttf
        weight: 600
